//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visitz.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visitz.Resources.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notes.
        /// </summary>
        public static string AddNotes {
            get {
                return ResourceManager.GetString("AddNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caseload.
        /// </summary>
        public static string Caseload {
            get {
                return ResourceManager.GetString("Caseload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All clear! Nothing is assigned to you..
        /// </summary>
        public static string CaseloadIsEmpty {
            get {
                return ResourceManager.GetString("CaseloadIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by key player&apos;s name.
        /// </summary>
        public static string CaseloadSearchHint {
            get {
                return ResourceManager.GetString("CaseloadSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case type.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character limit reached.
        /// </summary>
        public static string CharacterLimitReached {
            get {
                return ResourceManager.GetString("CharacterLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected—no internet available.
        /// </summary>
        public static string ConnectedNoInternet {
            get {
                return ResourceManager.GetString("ConnectedNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCFD Mobility contains Private Information and may only be accessed by authorized users..
        /// </summary>
        public static string DeviceAuthReason {
            get {
                return ResourceManager.GetString("DeviceAuthReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock MCFD Mobility.
        /// </summary>
        public static string DeviceAuthTitle {
            get {
                return ResourceManager.GetString("DeviceAuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft saved.
        /// </summary>
        public static string DraftSaved {
            get {
                return ResourceManager.GetString("DraftSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable device security.
        /// </summary>
        public static string EnableDeviceSecurity {
            get {
                return ResourceManager.GetString("EnableDeviceSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Publishing to ICM failed.
        /// </summary>
        public static string FailedToPublishToIcm {
            get {
                return ResourceManager.GetString("FailedToPublishToIcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Refreshing notes on device failed.
        /// </summary>
        public static string FailedToRefreshNotes {
            get {
                return ResourceManager.GetString("FailedToRefreshNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family members.
        /// </summary>
        public static string FamilyMembers {
            get {
                return ResourceManager.GetString("FamilyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an unpublished draft.
        /// </summary>
        public static string HaveUnpublishedDraft {
            get {
                return ResourceManager.GetString("HaveUnpublishedDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry.
        /// </summary>
        public static string InvalidEntry {
            get {
                return ResourceManager.GetString("InvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key player.
        /// </summary>
        public static string KeyPlayer {
            get {
                return ResourceManager.GetString("KeyPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully logged in.
        ///
        ///However, you currently aren&apos;t authorized to use MCFD Mobility. Please request access and try again later..
        /// </summary>
        public static string LoginSuccessButUnauth {
            get {
                return ResourceManager.GetString("LoginSuccessButUnauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out and clear data.
        /// </summary>
        public static string LogoutAndClearData {
            get {
                return ResourceManager.GetString("LogoutAndClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached ICM data on this device will be cleared and you will need to log in again before using any ICM features over the internet.
        ///
        ///Logging out won&apos;t affect your unpublished notes..
        /// </summary>
        public static string LogoutAndClearDataDesc {
            get {
                return ResourceManager.GetString("LogoutAndClearDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet available.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no notes for this {0}.
        /// </summary>
        public static string NoNotesForEntity {
            get {
                return ResourceManager.GetString("NoNotesForEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no notes for {0}.
        /// </summary>
        public static string NoNotesForPeriod {
            get {
                return ResourceManager.GetString("NoNotesForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for &apos;{0}&apos;.
        /// </summary>
        public static string NoResultsForSearch {
            get {
                return ResourceManager.GetString("NoResultsForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        public static string NoResultsForSearchAndFilter {
            get {
                return ResourceManager.GetString("NoResultsForSearchAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        public static string NotePageNumberHeader {
            get {
                return ResourceManager.GetString("NotePageNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Notes published to ICM.
        /// </summary>
        public static string NotesPublishedToIcm {
            get {
                return ResourceManager.GetString("NotesPublishedToIcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open date.
        /// </summary>
        public static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing notes to ICM.
        /// </summary>
        public static string PublishingNotesToIcm {
            get {
                return ResourceManager.GetString("PublishingNotesToIcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to ICM.
        /// </summary>
        public static string PublishToIcm {
            get {
                return ResourceManager.GetString("PublishToIcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull to refresh caseload from ICM.
        /// </summary>
        public static string PullToRefreshCaseload {
            get {
                return ResourceManager.GetString("PullToRefreshCaseload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCFD Mobility is unable to access downloaded copies of ICM data due to an unexpected event. This error can&apos;t be recovered from.
        ///
        ///Downloaded copies of ICM data will be deleted.
        ///
        ///To continue using the app: open the app switcher, force close MCFD Mobility, then launch it again..
        /// </summary>
        public static string RealmDatabaseErrorMessage {
            get {
                return ResourceManager.GetString("RealmDatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart app to fix data issue.
        /// </summary>
        public static string RealmDatabaseErrorTitle {
            get {
                return ResourceManager.GetString("RealmDatabaseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Refreshed notes on device.
        /// </summary>
        public static string RefreshedNotesOnDevice {
            get {
                return ResourceManager.GetString("RefreshedNotesOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing notes.
        /// </summary>
        public static string RefreshingNotes {
            get {
                return ResourceManager.GetString("RefreshingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety assessment.
        /// </summary>
        public static string SafetyAssessment {
            get {
                return ResourceManager.GetString("SafetyAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Parent/care-provider caused serious physical harm to the child/youth, or made a plausible threat to cause serious physical harm in the current report indicated by.
        /// </summary>
        public static string SafetyFactor1 {
            get {
                return ResourceManager.GetString("SafetyFactor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Current circumstances, combined with information that the parent/care-provider has or may have previously maltreated (abuse or neglect) a child/youth in his/her care, suggest that the child/youth&apos;s safety may be of immediate concern based on the severity of the previous maltreatment or the parent/care-provider&apos;s response to the previous incident.
        /// </summary>
        public static string SafetyFactor2 {
            get {
                return ResourceManager.GetString("SafetyFactor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCFD Mobility requires your device to be secured by passcode, biometrics, or other security. Enable security in your device settings and try again..
        /// </summary>
        public static string SecureDeviceAndTryAgain {
            get {
                return ResourceManager.GetString("SecureDeviceAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string Subtype_ChildProtectionIncidentInitials {
            get {
                return ResourceManager.GetString("Subtype_ChildProtectionIncidentInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        public static string Subtype_ChildServicesInitials {
            get {
                return ResourceManager.GetString("Subtype_ChildServicesInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FS.
        /// </summary>
        public static string Subtype_FamilyServicesInitials {
            get {
                return ResourceManager.GetString("Subtype_FamilyServicesInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to select.
        /// </summary>
        public static string TapToSelect {
            get {
                return ResourceManager.GetString("TapToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate session.
        /// </summary>
        public static string TerminateSession {
            get {
                return ResourceManager.GetString("TerminateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t authorized to use this feature..
        /// </summary>
        public static string UnauthorizedForApi {
            get {
                return ResourceManager.GetString("UnauthorizedForApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled IDIR login..
        /// </summary>
        public static string UserCancelledAuth {
            get {
                return ResourceManager.GetString("UserCancelledAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are authorized to use MCFD Mobility..
        /// </summary>
        public static string YouAreAuthorized {
            get {
                return ResourceManager.GetString("YouAreAuthorized", resourceCulture);
            }
        }
    }
}
