<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>$(VisitzVersion)</Version>
	</PropertyGroup>

	<Import Project="..\Visitz\Visitz.props" />

	<ItemGroup>
		<PackageReference Include="MimeTypes" Version="2.5.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SecurityCodeScan.VS2019" Version="$(SecurityCodeScanVersion)">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SharpSource" Version="$(SharpSourceVersion)" PrivateAssets="All" />
	</ItemGroup>

</Project>
