<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>2.5.0</Version>
	</PropertyGroup>

	<Import Project="..\Visitz\Visitz.props" />

	<ItemGroup>
		<PackageReference Include="SecurityCodeScan.VS2019" Version="$(SecurityCodeScanVersion)">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SharpSource" Version="1.24.0" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\SafetyAssess\" />
	</ItemGroup>

</Project>
