//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitzModel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaseTypeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaseTypeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitzModel.Resources.Localization.CaseTypeStrings", typeof(CaseTypeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoption home.
        /// </summary>
        public static string AdoptionHome {
            get {
                return ResourceManager.GetString("AdoptionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoption service.
        /// </summary>
        public static string AdoptionService {
            get {
                return ResourceManager.GetString("AdoptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment only.
        /// </summary>
        public static string AssessmentOnly {
            get {
                return ResourceManager.GetString("AssessmentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted adoption.
        /// </summary>
        public static string AssistedAdoption {
            get {
                return ResourceManager.GetString("AssistedAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autism.
        /// </summary>
        public static string Autism {
            get {
                return ResourceManager.GetString("Autism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child At Home program.
        /// </summary>
        public static string ChildAtHomeProgram {
            get {
                return ResourceManager.GetString("ChildAtHomeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child services.
        /// </summary>
        public static string ChildServices {
            get {
                return ResourceManager.GetString("ChildServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYSN family services.
        /// </summary>
        public static string CysnFamilyServices {
            get {
                return ResourceManager.GetString("CysnFamilyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family services.
        /// </summary>
        public static string FamilyServices {
            get {
                return ResourceManager.GetString("FamilyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical benefits.
        /// </summary>
        public static string MedicalBenefits {
            get {
                return ResourceManager.GetString("MedicalBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post adoption service.
        /// </summary>
        public static string PostAdoptionService {
            get {
                return ResourceManager.GetString("PostAdoptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post majority services.
        /// </summary>
        public static string PostMajorityServices {
            get {
                return ResourceManager.GetString("PostMajorityServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support needs children youth.
        /// </summary>
        public static string SupportNeedsChildrenYouth {
            get {
                return ResourceManager.GetString("SupportNeedsChildrenYouth", resourceCulture);
            }
        }
    }
}
