//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitzModel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntitySubtypeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitySubtypeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitzModel.Resources.Localization.EntitySubtypeStrings", typeof(EntitySubtypeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoption home.
        /// </summary>
        internal static string AdoptionHome {
            get {
                return ResourceManager.GetString("AdoptionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adoption service.
        /// </summary>
        internal static string AdoptionService {
            get {
                return ResourceManager.GetString("AdoptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours.
        /// </summary>
        internal static string AfterHours {
            get {
                return ResourceManager.GetString("AfterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours - Action.
        /// </summary>
        internal static string AfterHoursAction {
            get {
                return ResourceManager.GetString("AfterHoursAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours - From.
        /// </summary>
        internal static string AfterHoursFrom {
            get {
                return ResourceManager.GetString("AfterHoursFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours - Info.
        /// </summary>
        internal static string AfterHoursInfo {
            get {
                return ResourceManager.GetString("AfterHoursInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement with young adults.
        /// </summary>
        internal static string AgreementWithYoungAdults {
            get {
                return ResourceManager.GetString("AgreementWithYoungAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment only.
        /// </summary>
        internal static string AssessmentOnly {
            get {
                return ResourceManager.GetString("AssessmentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted adoption.
        /// </summary>
        internal static string AssistedAdoption {
            get {
                return ResourceManager.GetString("AssistedAdoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autism.
        /// </summary>
        internal static string Autism {
            get {
                return ResourceManager.GetString("Autism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autism Funding Unit.
        /// </summary>
        internal static string AutismFundingUnit {
            get {
                return ResourceManager.GetString("AutismFundingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralized Services Hub.
        /// </summary>
        internal static string CentralizedServicesHub {
            get {
                return ResourceManager.GetString("CentralizedServicesHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child At Home program.
        /// </summary>
        internal static string ChildAtHomeProgram {
            get {
                return ResourceManager.GetString("ChildAtHomeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child protection.
        /// </summary>
        internal static string ChildProtection {
            get {
                return ResourceManager.GetString("ChildProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child services.
        /// </summary>
        internal static string ChildServices {
            get {
                return ResourceManager.GetString("ChildServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community development.
        /// </summary>
        internal static string CommunityDevelopment {
            get {
                return ResourceManager.GetString("CommunityDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYSN.
        /// </summary>
        internal static string Cysn {
            get {
                return ResourceManager.GetString("Cysn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYSN family services.
        /// </summary>
        internal static string CysnFamilyServices {
            get {
                return ResourceManager.GetString("CysnFamilyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Needs assessment.
        /// </summary>
        internal static string FamilyNeedsAssessment {
            get {
                return ResourceManager.GetString("FamilyNeedsAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family services.
        /// </summary>
        internal static string FamilyServices {
            get {
                return ResourceManager.GetString("FamilyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical benefits.
        /// </summary>
        internal static string MedicalBenefits {
            get {
                return ResourceManager.GetString("MedicalBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post adoption service.
        /// </summary>
        internal static string PostAdoptionService {
            get {
                return ResourceManager.GetString("PostAdoptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post majority services.
        /// </summary>
        internal static string PostMajorityServices {
            get {
                return ResourceManager.GetString("PostMajorityServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol investigation.
        /// </summary>
        internal static string ProtocolInvestigation {
            get {
                return ResourceManager.GetString("ProtocolInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral and inquiry.
        /// </summary>
        internal static string ReferralAndInquiry {
            get {
                return ResourceManager.GetString("ReferralAndInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for family suppot.
        /// </summary>
        internal static string RequestForFamilySupport {
            get {
                return ResourceManager.GetString("RequestForFamilySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for information.
        /// </summary>
        internal static string RequestForInformation {
            get {
                return ResourceManager.GetString("RequestForInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service: CAPP.
        /// </summary>
        internal static string RequestServiceCapp {
            get {
                return ResourceManager.GetString("RequestServiceCapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service - CFS.
        /// </summary>
        internal static string RequestServiceCfs {
            get {
                return ResourceManager.GetString("RequestServiceCfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening.
        /// </summary>
        internal static string Screening {
            get {
                return ResourceManager.GetString("Screening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support needs children youth.
        /// </summary>
        internal static string SupportNeedsChildrenYouth {
            get {
                return ResourceManager.GetString("SupportNeedsChildrenYouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Needs request.
        /// </summary>
        internal static string SupportNeedsRequest {
            get {
                return ResourceManager.GetString("SupportNeedsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Services.
        /// </summary>
        internal static string YouthServices {
            get {
                return ResourceManager.GetString("YouthServices", resourceCulture);
            }
        }
    }
}
