//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitzModel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MemoTypeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemoTypeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitzModel.Resources.Localization.MemoTypeStrings", typeof(MemoTypeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours - Action.
        /// </summary>
        internal static string AfterHoursAction {
            get {
                return ResourceManager.GetString("AfterHoursAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours - From.
        /// </summary>
        internal static string AfterHoursFrom {
            get {
                return ResourceManager.GetString("AfterHoursFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours - Info.
        /// </summary>
        internal static string AfterHoursInfo {
            get {
                return ResourceManager.GetString("AfterHoursInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement with young adults.
        /// </summary>
        internal static string AgreementWithYoungAdults {
            get {
                return ResourceManager.GetString("AgreementWithYoungAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralized Services Hub.
        /// </summary>
        internal static string CentralizedServicesHub {
            get {
                return ResourceManager.GetString("CentralizedServicesHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYSN.
        /// </summary>
        internal static string Cysn {
            get {
                return ResourceManager.GetString("Cysn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol investigation.
        /// </summary>
        internal static string ProtocolInvestigation {
            get {
                return ResourceManager.GetString("ProtocolInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening.
        /// </summary>
        internal static string Screening {
            get {
                return ResourceManager.GetString("Screening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Needs request.
        /// </summary>
        internal static string SupportNeedsRequest {
            get {
                return ResourceManager.GetString("SupportNeedsRequest", resourceCulture);
            }
        }
    }
}
