//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitzModel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonVisitDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonVisitDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitzModel.Resources.Localization.PersonVisitDetails", typeof(PersonVisitDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption to private visit - Child declined to meet.
        /// </summary>
        public static string ExemptionChildDeclined {
            get {
                return ResourceManager.GetString("ExemptionChildDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption to private visit - Other.
        /// </summary>
        public static string ExemptionOther {
            get {
                return ResourceManager.GetString("ExemptionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Visit in the home.
        /// </summary>
        public static string NotPrivateInHome {
            get {
                return ResourceManager.GetString("NotPrivateInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Planning meeting.
        /// </summary>
        public static string NotPrivatePlanning {
            get {
                return ResourceManager.GetString("NotPrivatePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Relational visit.
        /// </summary>
        public static string NotPrivateRelational {
            get {
                return ResourceManager.GetString("NotPrivateRelational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Visit with caregiver.
        /// </summary>
        public static string NotPrivateWithCaregiver {
            get {
                return ResourceManager.GetString("NotPrivateWithCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit age 0-5.
        /// </summary>
        public static string PrivateAge0_5 {
            get {
                return ResourceManager.GetString("PrivateAge0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit in home.
        /// </summary>
        public static string PrivateInHome {
            get {
                return ResourceManager.GetString("PrivateInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit medical or support needs.
        /// </summary>
        public static string PrivateMedicalSupportNeeds {
            get {
                return ResourceManager.GetString("PrivateMedicalSupportNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit not in home.
        /// </summary>
        public static string PrivateNotInHome {
            get {
                return ResourceManager.GetString("PrivateNotInHome", resourceCulture);
            }
        }
    }
}
