//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitzModel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonVisitDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonVisitDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitzModel.Resources.Localization.PersonVisitDetails", typeof(PersonVisitDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption to private visit - Child declined to meet.
        /// </summary>
        public static string Api_ExemptionChildDeclined {
            get {
                return ResourceManager.GetString("Api_ExemptionChildDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption to private visit - Other.
        /// </summary>
        public static string Api_ExemptionOther {
            get {
                return ResourceManager.GetString("Api_ExemptionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Visit in the home.
        /// </summary>
        public static string Api_NotPrivateInHome {
            get {
                return ResourceManager.GetString("Api_NotPrivateInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Planning meeting.
        /// </summary>
        public static string Api_NotPrivatePlanning {
            get {
                return ResourceManager.GetString("Api_NotPrivatePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Relational visit.
        /// </summary>
        public static string Api_NotPrivateRelational {
            get {
                return ResourceManager.GetString("Api_NotPrivateRelational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private - Visit with caregiver.
        /// </summary>
        public static string Api_NotPrivateWithCaregiver {
            get {
                return ResourceManager.GetString("Api_NotPrivateWithCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit age 0-5.
        /// </summary>
        public static string Api_PrivateVisitAge0_5 {
            get {
                return ResourceManager.GetString("Api_PrivateVisitAge0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit in home.
        /// </summary>
        public static string Api_PrivateVisitInHome {
            get {
                return ResourceManager.GetString("Api_PrivateVisitInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit medical or support needs.
        /// </summary>
        public static string Api_PrivateVisitMedicalSupportNeeds {
            get {
                return ResourceManager.GetString("Api_PrivateVisitMedicalSupportNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit not in home.
        /// </summary>
        public static string Api_PrivateVisitNotInHome {
            get {
                return ResourceManager.GetString("Api_PrivateVisitNotInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age 0-5.
        /// </summary>
        public static string Details_Age0To5 {
            get {
                return ResourceManager.GetString("Details_Age0To5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child declined to meet.
        /// </summary>
        public static string Details_ChildDeclinedToMeet {
            get {
                return ResourceManager.GetString("Details_ChildDeclinedToMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in home.
        /// </summary>
        public static string Details_InHome {
            get {
                return ResourceManager.GetString("Details_InHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medical or support needs.
        /// </summary>
        public static string Details_MedicalOrSupportNeeds {
            get {
                return ResourceManager.GetString("Details_MedicalOrSupportNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not in home.
        /// </summary>
        public static string Details_NotInHome {
            get {
                return ResourceManager.GetString("Details_NotInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Details_Other {
            get {
                return ResourceManager.GetString("Details_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning meeting.
        /// </summary>
        public static string Details_PlanningMeeting {
            get {
                return ResourceManager.GetString("Details_PlanningMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relational visit.
        /// </summary>
        public static string Details_RelationalVisit {
            get {
                return ResourceManager.GetString("Details_RelationalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit in the home.
        /// </summary>
        public static string Details_VisitInTheHome {
            get {
                return ResourceManager.GetString("Details_VisitInTheHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit with caregiver.
        /// </summary>
        public static string Details_VisitWithCaregiver {
            get {
                return ResourceManager.GetString("Details_VisitWithCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemption to private visit.
        /// </summary>
        public static string Type_ExemptionToPrivateVisit {
            get {
                return ResourceManager.GetString("Type_ExemptionToPrivateVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not private.
        /// </summary>
        public static string Type_NotPrivate {
            get {
                return ResourceManager.GetString("Type_NotPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private visit.
        /// </summary>
        public static string Type_PrivateVisit {
            get {
                return ResourceManager.GetString("Type_PrivateVisit", resourceCulture);
            }
        }
    }
}
