//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitzModel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceRequestTypeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceRequestTypeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisitzModel.Resources.Localization.ServiceRequestTypeStrings", typeof(ServiceRequestTypeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After hours.
        /// </summary>
        public static string AfterHours {
            get {
                return ResourceManager.GetString("AfterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autism Funding Unit.
        /// </summary>
        public static string AutismFundingUnit {
            get {
                return ResourceManager.GetString("AutismFundingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community development.
        /// </summary>
        public static string CommunityDevelopment {
            get {
                return ResourceManager.GetString("CommunityDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Needs assessment.
        /// </summary>
        public static string FamilyNeedsAssessment {
            get {
                return ResourceManager.GetString("FamilyNeedsAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical benefits.
        /// </summary>
        public static string MedicalBenefits {
            get {
                return ResourceManager.GetString("MedicalBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Majority Services.
        /// </summary>
        public static string PostMajorityServices {
            get {
                return ResourceManager.GetString("PostMajorityServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for family suppot.
        /// </summary>
        public static string RequestForFamilySupport {
            get {
                return ResourceManager.GetString("RequestForFamilySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for information.
        /// </summary>
        public static string RequestForInformation {
            get {
                return ResourceManager.GetString("RequestForInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service: CAPP.
        /// </summary>
        public static string RequestServiceCapp {
            get {
                return ResourceManager.GetString("RequestServiceCapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service - CFS.
        /// </summary>
        public static string RequestServiceCfs {
            get {
                return ResourceManager.GetString("RequestServiceCfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Services.
        /// </summary>
        public static string YouthServices {
            get {
                return ResourceManager.GetString("YouthServices", resourceCulture);
            }
        }
    }
}
