<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>

		<UseMaui>true</UseMaui>
		<SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>

		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IdentityModel.OidcClient" Version="5.2.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.6" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.6" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
	</ItemGroup>

</Project>
