using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RealmBindingGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class RealmBindingSourceGenerator : IIncrementalGenerator
{
    private const string RealmObjectInterfaceMetadataName =
        "Realms.IRealmObject";

    private const string OptInAttributeMetadataName =
        "RealmBindings.GenerateRealmBindingsAttribute";

    private const string OptInAttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace RealmBindings
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class,
                AllowMultiple = false,
                Inherited = false)]
            internal sealed class GenerateRealmBindingsAttribute
                : global::System.Attribute
            {
            }
        }
        """;

    public void Initialize(
        IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(
            static initializationContext =>
            {
                initializationContext.AddSource(
                    "GenerateRealmBindingsAttribute.g.cs",
                    SourceText.From(
                        OptInAttributeSource,
                        Encoding.UTF8));
            });

        IncrementalValueProvider<INamedTypeSymbol?> realmObjectInterface =
            context.CompilationProvider.Select(
                static (compilation, _) =>
                    compilation.GetTypeByMetadataName(
                        RealmObjectInterfaceMetadataName));

        IncrementalValuesProvider<INamedTypeSymbol> attributedClasses =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName:
                    OptInAttributeMetadataName,
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax,
                transform: static (attributeContext, _) =>
                    (INamedTypeSymbol)attributeContext.TargetSymbol);

        IncrementalValuesProvider<ClassGenerationInfo?> classes =
            attributedClasses
                .Combine(realmObjectInterface)
                .Select(
                    static (pair, cancellationToken) =>
                        CreateClassGenerationInfo(
                            pair.Left,
                            pair.Right,
                            cancellationToken));

        context.RegisterSourceOutput(
            classes,
            (productionContext, classInfo) =>
            {
                if (classInfo is ClassGenerationInfo info)
                {
                    string source = GenerateSource(info);

                    productionContext.AddSource(
                        info.HintName,
                        SourceText.From(source, Encoding.UTF8));
                }
            });
    }

    private static ClassGenerationInfo? CreateClassGenerationInfo(
        INamedTypeSymbol classSymbol,
        INamedTypeSymbol? realmObjectInterface,
        CancellationToken cancellationToken)
    {
        if (realmObjectInterface is null)
        {
            return null;
        }

        if (classSymbol.TypeKind != TypeKind.Class)
        {
            return null;
        }

        if (!IsPartial(classSymbol, cancellationToken))
        {
            return null;
        }

        if (!AreContainingTypesPartial(
                classSymbol,
                cancellationToken))
        {
            return null;
        }

        if (!ImplementsInterface(
                classSymbol,
                realmObjectInterface))
        {
            return null;
        }

        ImmutableArray<PropertyGenerationInfo> properties =
            GetProperties(
                classSymbol,
                cancellationToken);

        if (properties.IsDefaultOrEmpty)
        {
            return null;
        }

        string? namespaceName =
            classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

        ImmutableArray<TypeGenerationInfo> containingTypes =
            GetContainingTypes(classSymbol);

        string fullyQualifiedTypeName =
            classSymbol.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);

        string hintName =
            SanitizeHintName(
                $"{fullyQualifiedTypeName}.RealmBindings.g.cs");

        return new ClassGenerationInfo(
            namespaceName,
            containingTypes,
            properties,
            hintName);
    }

    private static ImmutableArray<PropertyGenerationInfo> GetProperties(
        INamedTypeSymbol classSymbol,
        CancellationToken cancellationToken)
    {
        var properties =
            ImmutableArray.CreateBuilder<PropertyGenerationInfo>();

        foreach (IPropertySymbol propertySymbol in
                 classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (!IsSupportedProperty(propertySymbol))
            {
                continue;
            }

            string bindingPropertyName =
                propertySymbol.Name + "Binding";

            if (classSymbol
                .GetMembers(bindingPropertyName)
                .Length != 0)
            {
                continue;
            }

            string fallbackExpression =
                GetFallbackExpression(
                    propertySymbol,
                    cancellationToken);

            string propertyType =
                propertySymbol.Type.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat);

            properties.Add(
                new PropertyGenerationInfo(
                    propertyType: propertyType,
                    propertyName:
                        EscapeIdentifier(propertySymbol.Name),
                    bindingPropertyName:
                        EscapeIdentifier(bindingPropertyName),
                    accessibility:
                        GetAccessibility(
                            propertySymbol.DeclaredAccessibility),
                    fallbackExpression:
                        fallbackExpression));
        }

        return properties.ToImmutable();
    }

    private static bool IsSupportedProperty(
        IPropertySymbol property)
    {
        if (property.IsStatic)
        {
            return false;
        }

        if (property.IsIndexer)
        {
            return false;
        }

        if (property.ExplicitInterfaceImplementations.Length != 0)
        {
            return false;
        }

        if (property.GetMethod is null)
        {
            return false;
        }

        if (property.SetMethod is null)
        {
            return false;
        }

        if (property.SetMethod.IsInitOnly)
        {
            return false;
        }

        // Getter and setter must be public for Realm schema mapping
        if (property.GetMethod.DeclaredAccessibility != Accessibility.Public ||
            property.SetMethod.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        // Validate that the property type is supported by Realm
        if (!IsSupportedPropertyType(property.Type))
        {
            return false;
        }

        return true;
    }

    private static bool IsSupportedPropertyType(ITypeSymbol propertyType)
    {
        // Check for supported primitive and scalar types
        if (IsSupportedScalarType(propertyType))
        {
            return true;
        }

        // Check for IRealmObject or derived types
        if (IsRealmObject(propertyType))
        {
            return true;
        }

        // Check for supported collection types
        if (IsSupportedCollectionType(propertyType))
        {
            return true;
        }

        return false;
    }

    private static bool IsSupportedScalarType(ITypeSymbol type)
    {
        // Handle nullable types
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullableType)
        {
            return IsSupportedScalarType(nullableType.TypeArguments[0]);
        }

        // Supported primitive types
        return type.SpecialType switch
        {
            SpecialType.System_Boolean or
            SpecialType.System_Byte or
            SpecialType.System_SByte or
            SpecialType.System_Int16 or
            SpecialType.System_UInt16 or
            SpecialType.System_Int32 or
            SpecialType.System_UInt32 or
            SpecialType.System_Int64 or
            SpecialType.System_UInt64 or
            SpecialType.System_Single or
            SpecialType.System_Double or
            SpecialType.System_Decimal or
            SpecialType.System_String or
            SpecialType.System_DateTime => true,

            _ => IsSupportedNamedType(type)
        };
    }

    private static bool IsSupportedNamedType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        string fullName = namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Supported named types
        return fullName switch
        {
            "System.DateTimeOffset" or
            "System.Guid" or
            "System.Byte[]" or
            "System.Collections.Generic.IList<System.Byte>" or
            "MongoDB.Bson.ObjectId" => true,

            _ => false
        };
    }

    private static bool IsRealmObject(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        // Unwrap nullable types
        if (namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            namedType = (INamedTypeSymbol)namedType.TypeArguments[0];
        }

        // Check if it implements IRealmObject
        string realmObjectInterface = "Realms.IRealmObject";
        foreach (INamedTypeSymbol interfaceSymbol in namedType.AllInterfaces)
        {
            if (interfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == realmObjectInterface)
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsSupportedCollectionType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        string originalDefinition = namedType.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // IList<T>, ISet<T>, IDictionary<K,V> are supported
        bool isIList = originalDefinition == "System.Collections.Generic.IList<T>";
        bool isISet = originalDefinition == "System.Collections.Generic.ISet<T>";
        bool isIDictionary = originalDefinition == "System.Collections.Generic.IDictionary<TKey, TValue>";

        if (!isIList && !isISet && !isIDictionary)
        {
            return false;
        }

        // Validate collection element types
        if (isIList || isISet)
        {
            ITypeSymbol elementType = namedType.TypeArguments[0];
            // Collections cannot contain collections
            if (IsSupportedCollectionType(elementType))
            {
                return false;
            }
            return IsSupportedScalarType(elementType) || IsRealmObject(elementType);
        }

        if (isIDictionary)
        {
            ITypeSymbol keyType = namedType.TypeArguments[0];
            ITypeSymbol valueType = namedType.TypeArguments[1];

            // Dictionary keys must be scalar types, not collections
            if (!IsSupportedScalarType(keyType) || IsSupportedCollectionType(keyType))
            {
                return false;
            }

            // Dictionary values: scalar types or Realm objects
            // Note: Collections cannot be dictionary values
            if (IsSupportedCollectionType(valueType))
            {
                return false;
            }

            return IsSupportedScalarType(valueType) || IsRealmObject(valueType);
        }

        return false;
    }

    private static string GetFallbackExpression(
        IPropertySymbol propertySymbol,
        CancellationToken cancellationToken)
    {
        foreach (SyntaxReference syntaxReference in
                 propertySymbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax(cancellationToken)
                is not PropertyDeclarationSyntax propertySyntax)
            {
                continue;
            }

            if (propertySyntax.Initializer is null)
            {
                continue;
            }

            return propertySyntax.Initializer.Value
                .WithoutTrivia()
                .ToFullString();
        }

        return "default";
    }

    private static bool ImplementsInterface(
        INamedTypeSymbol classSymbol,
        INamedTypeSymbol interfaceSymbol)
    {
        return classSymbol.AllInterfaces.Any(
            implementedInterface =>
                SymbolEqualityComparer.Default.Equals(
                    implementedInterface,
                    interfaceSymbol));
    }

    private static bool IsPartial(
        INamedTypeSymbol typeSymbol,
        CancellationToken cancellationToken)
    {
        foreach (SyntaxReference syntaxReference in
                 typeSymbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax(cancellationToken)
                    is TypeDeclarationSyntax declaration &&
                declaration.Modifiers.Any(
                    SyntaxKind.PartialKeyword))
            {
                return true;
            }
        }

        return false;
    }

    private static bool AreContainingTypesPartial(
        INamedTypeSymbol classSymbol,
        CancellationToken cancellationToken)
    {
        for (INamedTypeSymbol? containingType =
                 classSymbol.ContainingType;
             containingType is not null;
             containingType = containingType.ContainingType)
        {
            if (!IsPartial(
                    containingType,
                    cancellationToken))
            {
                return false;
            }
        }

        return true;
    }

    private static ImmutableArray<TypeGenerationInfo>
        GetContainingTypes(INamedTypeSymbol targetType)
    {
        var types =
            new Stack<TypeGenerationInfo>();

        for (INamedTypeSymbol? current = targetType;
             current is not null;
             current = current.ContainingType)
        {
            types.Push(
                new TypeGenerationInfo(
                    keyword: GetTypeKeyword(current),
                    name: EscapeIdentifier(current.Name),
                    typeParameters:
                        GetTypeParameterList(current)));
        }

        return types.ToImmutableArray();
    }

    private static string GenerateSource(
        ClassGenerationInfo classInfo)
    {
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated />");
        source.AppendLine("using VisitzModel.Extensions;");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        int indentationLevel = 0;

        if (classInfo.NamespaceName is not null)
        {
            source.Append("namespace ")
                .Append(classInfo.NamespaceName)
                .AppendLine();

            source.AppendLine("{");

            indentationLevel++;
        }

        foreach (TypeGenerationInfo type in
                 classInfo.ContainingTypes)
        {
            AppendIndentation(
                source,
                indentationLevel);

            source.Append("partial ")
                .Append(type.Keyword)
                .Append(' ')
                .Append(type.Name)
                .Append(type.TypeParameters)
                .AppendLine();

            AppendIndentation(
                source,
                indentationLevel);

            source.AppendLine("{");

            indentationLevel++;
        }

        for (int index = 0;
             index < classInfo.Properties.Length;
             index++)
        {
            AppendProperty(
                source,
                classInfo.Properties[index],
                indentationLevel);

            if (index < classInfo.Properties.Length - 1)
            {
                source.AppendLine();
            }
        }

        for (int index =
                 classInfo.ContainingTypes.Length - 1;
             index >= 0;
             index--)
        {
            indentationLevel--;

            AppendIndentation(
                source,
                indentationLevel);

            source.AppendLine("}");
        }

        if (classInfo.NamespaceName is not null)
        {
            indentationLevel--;

            AppendIndentation(
                source,
                indentationLevel);

            source.AppendLine("}");
        }

        return source.ToString();
    }

    private static void AppendProperty(
        StringBuilder source,
        PropertyGenerationInfo property,
        int indentationLevel)
    {
        AppendIndentation(
            source,
            indentationLevel);

        if (!string.IsNullOrEmpty(property.Accessibility))
        {
            source.Append(property.Accessibility)
                .Append(' ');
        }

        source.Append(property.PropertyType)
            .Append(' ')
            .Append(property.BindingPropertyName)
            .AppendLine();

        AppendIndentation(
            source,
            indentationLevel);

        source.AppendLine("{");

        AppendIndentation(
            source,
            indentationLevel + 1);

        source.Append("get => IsValid ? ")
            .Append(property.PropertyName)
            .Append(" : ")
            .Append(property.FallbackExpression)
            .AppendLine(";");

        AppendIndentation(
            source,
            indentationLevel + 1);

        source.AppendLine("set");

        AppendIndentation(
            source,
            indentationLevel + 1);

        source.AppendLine("{");

        AppendIndentation(
            source,
            indentationLevel + 2);

        source.Append("this.Commit(() => ")
            .Append(property.PropertyName)
            .AppendLine(" = value);");

        AppendIndentation(
            source,
            indentationLevel + 2);

        source.Append("RaisePropertyChanged(nameof(")
            .Append(property.PropertyName)
            .AppendLine("));");

        AppendIndentation(
            source,
            indentationLevel + 1);

        source.AppendLine("}");

        AppendIndentation(
            source,
            indentationLevel);

        source.AppendLine("}");
    }

    private static string GetTypeKeyword(
        INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.IsRecord)
        {
            return typeSymbol.TypeKind == TypeKind.Struct
                ? "record struct"
                : "record";
        }

        return typeSymbol.TypeKind == TypeKind.Struct
            ? "struct"
            : "class";
    }

    private static string GetTypeParameterList(
        INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
        {
            return string.Empty;
        }

        return
            "<" +
            string.Join(
                ", ",
                typeSymbol.TypeParameters.Select(
                    static typeParameter =>
                        EscapeIdentifier(
                            typeParameter.Name))) +
            ">";
    }

    private static string GetAccessibility(
        Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public =>
                "public",

            Accessibility.Internal =>
                "internal",

            Accessibility.Private =>
                "private",

            Accessibility.Protected =>
                "protected",

            Accessibility.ProtectedOrInternal =>
                "protected internal",

            Accessibility.ProtectedAndInternal =>
                "private protected",

            _ =>
                string.Empty
        };
    }

    private static string EscapeIdentifier(
        string identifier)
    {
        bool isKeyword =
            SyntaxFacts.GetKeywordKind(identifier) !=
            SyntaxKind.None;

        bool isContextualKeyword =
            SyntaxFacts.GetContextualKeywordKind(identifier) !=
            SyntaxKind.None;

        return isKeyword || isContextualKeyword
            ? "@" + identifier
            : identifier;
    }

    private static string SanitizeHintName(
        string value)
    {
        var result = new StringBuilder(value.Length);

        foreach (char character in value)
        {
            result.Append(
                char.IsLetterOrDigit(character) ||
                character is '.' or '_' or '-'
                    ? character
                    : '_');
        }

        return result.ToString();
    }

    private static void AppendIndentation(
        StringBuilder source,
        int indentationLevel)
    {
        source.Append(
            ' ',
            indentationLevel * 4);
    }

    private readonly struct ClassGenerationInfo(
        string? namespaceName,
        ImmutableArray<TypeGenerationInfo> containingTypes,
        ImmutableArray<PropertyGenerationInfo> properties,
        string hintName)
    {
        public string? NamespaceName { get; } = namespaceName;
        public ImmutableArray<TypeGenerationInfo> ContainingTypes { get; } = containingTypes;
        public ImmutableArray<PropertyGenerationInfo> Properties { get; } = properties;
        public string HintName { get; } = hintName;
    }

    private readonly struct TypeGenerationInfo(
        string keyword,
        string name,
        string typeParameters)
    {
        public string Keyword { get; } = keyword;
        public string Name { get; } = name;
        public string TypeParameters { get; } = typeParameters;
    }

    private readonly struct PropertyGenerationInfo(
        string propertyType,
        string propertyName,
        string bindingPropertyName,
        string accessibility,
        string fallbackExpression)
    {
        public string PropertyType { get; } = propertyType;
        public string PropertyName { get; } = propertyName;
        public string BindingPropertyName { get; } = bindingPropertyName;
        public string Accessibility { get; } = accessibility;
        public string FallbackExpression { get; } = fallbackExpression;
    }
}
