<Project>

	<PropertyGroup>
		<CommunityToolkitMvvmVersion>8.2.2</CommunityToolkitMvvmVersion>
		<MauiPackageVersion>8.0.100</MauiPackageVersion>
		<NETTestSdkVersion>17.10.0</NETTestSdkVersion>
		<RealmVersion>12.2.0</RealmVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-ios|AnyCPU'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<ArchiveOnBuild>true</ArchiveOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<ArchiveOnBuild>true</ArchiveOnBuild>
	</PropertyGroup>

	<!-- If no BuildTypeColor was provided, use our default "developer build" color -->
	<PropertyGroup Condition=" '$(BuildTypeColor)' == '' ">
		<BuildTypeColor>#440066</BuildTypeColor>
	</PropertyGroup>

</Project>
