using VisitzApi.Models.Attachments;
using VisitzModel.Models.Attachments;
using VisitzModel.Models.EntityTypes;

namespace VisitzModelTest.Models.Attachments;

public class AttachmentTests
{
    private static readonly List<AttachmentJson> initialAttachmentJsonList =
    [
        new()
        {
            ApplicationNo = "123",
            AttachmentId = "1",
            CaseId = "2",
            Categorie = "Case",
            Category = "sasdas",
            ClientFlag = "d",
            Comments = "ssss",
            CreatedByName = "bhgbh",
            CreatedDate = "12/10/2018 13:50:02",
            EndDate = "12/10/2018 13:50:02",
            FileAutoUpdFlg = "rr",
            FileDate = "12/10/2018 13:50:02",
            FileDeferFlg = "d",
            FileDockReqFlg = "d",
            FileDockStatFlg = "d",
            FileExt = "jpg",
            FileName = "test",
            FileSize = "12",
            FileSrcPath = "ddd",
            FileSrcType = "dcs",
            FinalFlag = "d",
            FormDescription = "dfdsfs",
            Id = "1",
            IncidentId = "1",
            IncidentNo = "1",
            Internal = "1",
            LastUpdatedDate = "12/10/2018 13:50:02",
            MemoId = "1",
            MemoNumber = "1",
            NoIntervention = "ss",
            PortalVisible = "true",
            ShowOnContact = "true",
            SrId = "1",
            Status = "test",
            SubCategory = "test",
            Template = "jdaijd",
            TemplateType = "dsfs",
            UpdatedByName = "test",
        },
        new()
        {
            ApplicationNo = "123",
            AttachmentId = "2",
            CaseId = "2",
            Categorie = "Case",
            Category = "sasdas",
            ClientFlag = "d",
            Comments = "ssss",
            CreatedByName = "bhgbh",
            CreatedDate = "12/10/2018 13:50:02",
            EndDate = "12/10/2018 13:50:02",
            FileAutoUpdFlg = "rr",
            FileDate = "12/10/2018 13:50:02",
            FileDeferFlg = "d",
            FileDockReqFlg = "d",
            FileDockStatFlg = "d",
            FileExt = "jpg",
            FileName = "test",
            FileSize = "12",
            FileSrcPath = "ddd",
            FileSrcType = "dcs",
            FinalFlag = "d",
            FormDescription = "dfdsfs",
            Id = "2",
            IncidentId = "1",
            IncidentNo = "1",
            Internal = "1",
            LastUpdatedDate = "12/10/2018 13:50:02",
            MemoId = "1",
            MemoNumber = "1",
            NoIntervention = "ss",
            PortalVisible = "true",
            ShowOnContact = "true",
            SrId = "1",
            Status = "test",
            SubCategory = "test",
            Template = "jdaijd",
            TemplateType = "dsfs",
            UpdatedByName = "test",
        },
        new()
        {
            ApplicationNo = "123",
            AttachmentId = "1",
            CaseId = "2",
            Categorie = "Case",
            Category = "sasdas",
            ClientFlag = "d",
            Comments = "ssss",
            CreatedByName = "bhgbh",
            CreatedDate = "12/10/2018 13:50:02",
            EndDate = "12/10/2018 13:50:02",
            FileAutoUpdFlg = "rr",
            FileDate = "12/10/2018 13:50:02",
            FileDeferFlg = "d",
            FileDockReqFlg = "d",
            FileDockStatFlg = "d",
            FileExt = "jpg",
            FileName = "test",
            FileSize = "12",
            FileSrcPath = "ddd",
            FileSrcType = "dcs",
            FinalFlag = "d",
            FormDescription = "dfdsfs",
            Id = "3",
            IncidentId = "1",
            IncidentNo = "1",
            Internal = "1",
            LastUpdatedDate = "12/10/2018 13:50:02",
            MemoId = "1",
            MemoNumber = "1",
            NoIntervention = "ss",
            PortalVisible = "true",
            ShowOnContact = "true",
            SrId = "1",
            Status = "test",
            SubCategory = "test",
            Template = "jdaijd",
            TemplateType = "dsfs",
            UpdatedByName = "test",
        },
        new()
        {
            ApplicationNo = "123",
            AttachmentId = "1",
            CaseId = "2",
            Categorie = "Case",
            Category = "sasdas",
            ClientFlag = "d",
            Comments = "ssss",
            CreatedByName = "bhgbh",
            CreatedDate = "12/10/2018 13:50:02",
            EndDate = "12/10/2018 13:50:02",
            FileAutoUpdFlg = "rr",
            FileDate = "12/10/2018 13:50:02",
            FileDeferFlg = "d",
            FileDockReqFlg = "d",
            FileDockStatFlg = "d",
            FileExt = "jpg",
            FileName = "test",
            FileSize = "12",
            FileSrcPath = "ddd",
            FileSrcType = "dcs",
            FinalFlag = "d",
            FormDescription = "dfdsfs",
            Id = "4",
            IncidentId = "1",
            IncidentNo = "1",
            Internal = "1",
            LastUpdatedDate = "12/10/2018 13:50:02",
            MemoId = "1",
            MemoNumber = "1",
            NoIntervention = "ss",
            PortalVisible = "true",
            ShowOnContact = "true",
            SrId = "1",
            Status = "test",
            SubCategory = "test",
            Template = "jdaijd",
            TemplateType = "dsfs",
            UpdatedByName = "test",
        },
        new()
        {
            ApplicationNo = "123",
            AttachmentId = "10",
            CaseId = "2",
            Categorie = "Case",
            Category = "sasdas",
            ClientFlag = "d",
            Comments = "ssss",
            CreatedByName = "bhgbh",
            CreatedDate = "12/10/2018 13:50:02",
            EndDate = "12/10/2018 13:50:02",
            FileAutoUpdFlg = "rr",
            FileDate = "12/10/2018 13:50:02",
            FileDeferFlg = "d",
            FileDockReqFlg = "d",
            FileDockStatFlg = "d",
            FileExt = "jpg",
            FileName = "test",
            FileSize = "12",
            FileSrcPath = "ddd",
            FileSrcType = "dcs",
            FinalFlag = "d",
            FormDescription = "dfdsfs",
            Id = "10",
            IncidentId = "1",
            IncidentNo = "1",
            Internal = "1",
            LastUpdatedDate = "12/10/2018 13:50:02",
            MemoId = "1",
            MemoNumber = "1",
            NoIntervention = "ss",
            PortalVisible = "true",
            ShowOnContact = "true",
            SrId = "1",
            Status = "test",
            SubCategory = "test",
            Template = "jdaijd",
            TemplateType = "dsfs",
            UpdatedByName = "test",
        },
    ];

    [Fact]
    public async Task SynchronizeAsyncDeletesDifferenceFromRealm()
    {
        var realm = await TestingUtilities.MakeRealm<AttachmentTests>();
        List<AttachmentJson> attachments = new(initialAttachmentJsonList);
        string parentId = "12";

        await Attachment.SynchronizeAsync(realm, attachments, parentId, EntityType.Case);
        var numberOfAttachmentsBeforeDeletion = realm.All<Attachment>().Count();

        //Checking deletion of realm objects
        attachments = new(initialAttachmentJsonList);
        attachments.RemoveAll(item => item.Id == "4");

        await Attachment.SynchronizeAsync(realm, attachments, parentId, EntityType.Case);

        var numberOfAttachmentsAfterDeletion = realm.All<Attachment>().Count();

        Assert.Equal(5, numberOfAttachmentsBeforeDeletion);
        Assert.Equal(numberOfAttachmentsBeforeDeletion - 1, numberOfAttachmentsAfterDeletion);
    }
}
