name: Build Windows release package

run-name: Build Windows release package (${{ github.event.inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build package for'
        type: environment
        required: true

env:
  BASE_PROJPATH: "./visitz"
  PROJPATH: "visitz/Visitz"
  DOTNET_SDK_VERSION: "8.0.402"
  GLOBAL_JSON_PATH: "visitz/global.json"
  CERT_FILEPATH: "release-cert.pfx"

jobs:

  build-windows-package:
    name: Building and uploading MSIX to GitHub
    runs-on: windows-2022
    environment: ${{ inputs.environment }}
    timeout-minutes: 40
    env:
      # TODO: read "MCFD Mobility" app name from MSBuild instead
      OUTPUT_NAME: "MCFD Mobility-Windows-${{ github.event.inputs.environment }}-build_"
      OUTPUT_PATH: "/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/"
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Decode signing certificate
        env:
          certFilepath: ${{ env.CERT_FILEPATH }}
        run: |
          $encodedFilepath = "encoded-cert.txt"
          Set-Content $encodedFilepath -Value "${{ secrets.WINDOWS_RELEASE_CERT_BASE64 }}"
          certutil.exe -decode $encodedFilepath $env:certFilepath

      - name: Import signing certificate
        env:
          certFilepath: ${{ env.CERT_FILEPATH }}
        run: |
          $storeLoc = "Cert:\CurrentUser\My\"
          $pw = ConvertTo-SecureString -String "${{ secrets.WINDOWS_RELEASE_CERT_PASSWORD }}" -AsPlainText -Force
          Import-PfxCertificate -FilePath $env:certFilepath -CertStoreLocation $storeLoc -Password $pw

      - name: Offset build number
        run: |
          $newBuildNumber = ${{ github.run_number }} + ${{ vars.WINDOWS_BUILD_NUMBER_OFFSET }}
          echo "ADJUSTED_BUILD_NUMBER=$($newBuildNumber)" >> $env:GITHUB_ENV
          echo "OUTPUT_NAME=$($env:OUTPUT_NAME + $newBuildNumber)" >> $env:GITHUB_ENV

      - name: Inflate ${{ env.GLOBAL_JSON_PATH }}
        run: |
          Copy-Item .\${{ env.GLOBAL_JSON_PATH }}.template .\${{ env.GLOBAL_JSON_PATH }}

      - name: Force .NET SDK version ${{ env.DOTNET_SDK_VERSION }}
        uses: jossef/action-set-json-field@v2.2
        with:
          file: ${{ env.GLOBAL_JSON_PATH }}
          field: sdk.version
          value: ${{ env.DOTNET_SDK_VERSION }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Prepare NuGet
        run: |
          dotnet --version
          dotnet nuget locals all --clear

      - name: Cache .NET dependencies
        uses: actions/cache@v4.0.2
        if: always()
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install .NET MAUI workload
        working-directory: ${{ env.BASE_PROJPATH }}
        run: |
          dotnet --version
          dotnet workload install maui

      - name: .NET release build for Windows (${{ inputs.environment }})
        run: |
          dotnet publish $env:PROJPATH `
            --framework net8.0-windows10.0.19041.0 `
            --configuration Release `
            -p:ApplicationVersion=${{ env.ADJUSTED_BUILD_NUMBER }} `
            -p:DeploymentEnvironment=${{ vars.ENV_NAME }} `
            -p:PackageCertificateThumbprint=${{ secrets.WINDOWS_RELEASE_CERT_THUMBPRINT }} `
            -p:BuildTypeColor=${{ vars.BUILD_TYPE_COLOR }} `
            -p:RuntimeIdentifierOverride=win10-x64 `
            -p:UseAppSettings=true `
            -p:Oidc_AuthenticationDomain=${{ vars.AUTHENTICATION_DOMAIN }} `
            -p:Oidc_ClientId=${{ vars.KEYCLOAK_CLIENT_ID }} `
            -p:Oidc_RedirectUri=${{ vars.REDIRECT_URI }} `
            -p:Api_HttpsApiDomain=${{ vars.API_BASE_URL }} `
            -p:ContactInfo_MailToAuthorize=${{ secrets.MAILTO_AUTHORIZE }} `
            -p:ContactInfo_AccessRequestFormUrl="${{ vars.ACCESS_REQUEST_FORM_URL }}" `
            -p:ContactInfo_FeedbackSurveyUrl="${{ vars.FEEDBACK_SURVEY_URL }}" `
            -p:Debug_EnableDebugOptions=${{ vars.DEBUG_OPTIONS }}

      - name: Prepare output package
        run: |
          cd ${{ env.PROJPATH }}\${{ env.OUTPUT_PATH }}
          mv **\Visitz_*.msix ".\${{ env.OUTPUT_NAME }}.msix"

      - name: Upload MSIX (${{ inputs.environment }})
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ${{ env.PROJPATH }}\${{ env.OUTPUT_PATH }}\${{ env.OUTPUT_NAME }}.msix
