name: Build iOS release package

run-name: Build iOS release package (${{ github.event.inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build package for'
        type: environment
        required: true

env:
  BUILD_NUM_OFFSET: 246 # Final run number from previous repo before migration
  RUN_NUMBER: ${{ github.run_number }}
  PROJPATH: "visitz/Visitz"
  DOTNET_SDK_VERSION: "10.0.102"
  GLOBAL_JSON_PATH: "global.json"
  XCODE_VERSION: "26.2"

jobs:

  build-ios-package:
    name: Building, archiving and uploading IPA to GitHub
    runs-on: macOS-15
    environment: ${{ inputs.environment }}
    timeout-minutes: 200
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set build name
        run: |
          BUILD_NUM=$(($BUILD_NUM_OFFSET + $RUN_NUMBER))
          echo "BUILD_NUM=$BUILD_NUM" >> "$GITHUB_ENV"
          
          # TODO: read "MCFD Mobility" app name from MSBuild instead

          OUTPUT_NAME="MCFD Mobility-iOS-${{ github.event.inputs.environment }}-build_$BUILD_NUM"
          echo "OUTPUT_NAME=$OUTPUT_NAME" >> "$GITHUB_ENV"

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Import code-signing certificates
        uses: Apple-Actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64 }}
          p12-password: ${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_PASSWORD }}

      - name: Retrieve certificate name
        env:
          APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64: ${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64 }}
          TEMP_CERT_PATH: "temp-cert.p12"
        run: |
          echo -n "$APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64" | base64 --decode -o $TEMP_CERT_PATH

          SUBJECT=$(openssl pkcs12 -in "$TEMP_CERT_PATH" \
            -password pass:"${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_PASSWORD }}" \
            -nodes -nokeys \
            | openssl x509 -noout -subject)

          COMMON_NAME=$(./.github/scripts/get_common_name.sh "$SUBJECT")
          echo "IOS_BUILD_CERTIFICATE_NAME=$COMMON_NAME" >> "$GITHUB_ENV"

          rm $TEMP_CERT_PATH

      - name: Install provisioning profile and retrieve name
        env:
          IOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$IOS_BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          # Retrieve profile name
          echo "IOS_CODE_SIGN_PROVISION_PROFILE_NAME=$(/usr/libexec/PlistBuddy \
            -c 'Print Name' /dev/stdin \
            <<< $(security cms -D -i $PP_PATH))" >> "$GITHUB_ENV"

      - name: Inflate ${{ env.GLOBAL_JSON_PATH }}
        run: |
          cp ${{ env.GLOBAL_JSON_PATH }}.template ${{ env.GLOBAL_JSON_PATH }}

      - name: Force .NET SDK version ${{ env.DOTNET_SDK_VERSION }}
        uses: jossef/action-set-json-field@v2.2
        with:
          file: ${{ env.GLOBAL_JSON_PATH }}
          field: sdk.version
          value: ${{ env.DOTNET_SDK_VERSION }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Cache .NET dependencies
        uses: actions/cache@v4.2.4
        if: always()
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache .NET workloads
        uses: actions/cache@v4.2.4
        if: always()
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-workloads-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-workloads-

      - name: Install .NET MAUI ${{ env.MAUI_WORKLOAD_VERSION }} workloads
        run: |
          dotnet workload install maui maui-ios --version ${{ env.DOTNET_SDK_VERSION }}

      - name: .NET release build for iOS (${{ inputs.environment }})
        run: |
          dotnet publish $PROJPATH \
            --framework net10.0-ios \
            --configuration Release \
            -p:ApplicationVersion=${{ env.BUILD_NUM }} \
            -p:DeploymentEnvironment=${{ vars.ENV_NAME }} \
            -p:BuildTypeColor=${{ vars.BUILD_TYPE_COLOR }} \
            -p:CodesignKey="${{ env.IOS_BUILD_CERTIFICATE_NAME }}" \
            -p:CodesignProvision="${{ env.IOS_CODE_SIGN_PROVISION_PROFILE_NAME }}" \
            -p:UseAppSettings=true \
            -p:Oidc_AuthenticationDomain="${{ vars.AUTHENTICATION_DOMAIN }}" \
            -p:Oidc_ClientId="${{ vars.KEYCLOAK_CLIENT_ID }}" \
            -p:Oidc_RedirectUri="${{ vars.REDIRECT_URI }}" \
            -p:Api_HttpsApiDomain="${{ vars.API_BASE_URL }}" \
            -p:ContactInfo_MailToAuthorize="${{ secrets.MAILTO_AUTHORIZE }}" \
            -p:ContactInfo_AccessRequestFormUrl="${{ vars.ACCESS_REQUEST_FORM_URL }}" \
            -p:ContactInfo_FeedbackSurveyUrl="${{ vars.FEEDBACK_SURVEY_URL }}" \
            -p:Debug_EnableDebugOptions=${{ vars.DEBUG_OPTIONS }}

      - name: Prepare output package
        run: |
          cd ${{ env.PROJPATH }}/bin/Release/net10.0-ios/ios-arm64/publish
          mv "MCFD Mobility.ipa" "$OUTPUT_NAME.ipa"

      - name: Upload IPA archive (${{ inputs.environment }})
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ${{ env.PROJPATH }}/bin/Release/net10.0-ios/ios-arm64/publish/*.ipa
